services:
  - type: web
    name: spring-boot-admin-panel
    env: java
    region: oregon
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/spring-boot-portfolio-admin.jar"
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
